site_name: lyapy

theme:
  name: readthedocs

nav:
  - Lyappy: index.md
  - Lyappy (Português): pt/index.md

markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - css/custom.css

